apiVersion: channel.signoz.m.crossplane.io/v1beta1
kind: NotificationChannel
metadata:
  name: pagerduty-alerts
  namespace: default
  labels:
    team: platform
    environment: production
spec:
  forProvider:
    name: "PagerDuty Alerts"
    type: "pagerduty"
    pagerdutyConfigs:
      - severity: "critical"
        send_resolved: true
        routingKeySecretRef:
          name: pagerduty-secret
          namespace: default
          key: routing-key
  providerConfigRef:
    name: default
---
apiVersion: v1
kind: Secret
metadata:
  name: pagerduty-secret
  namespace: default
type: Opaque
stringData:
  routing-key: "your-pagerduty-routing-key"